_IBC/constantine-1-axelar-testnet.json
_IBC/constantine-1-osmosis-test-4.json
ibc_data_schema.json

Adds existing contantine-1 IBC connectiosn adn default IBC schema.json

feat: add existing constantine-1 IBC connections and default schema

---

.gitignore
constantine-2/README.md
utils/constantine-2-genesis.py
utils/genesis_lib.py

- Add automation scripts to generate genesis for constantine-2

Create constantine-2 genesis from constantine-1 hard fork

---

archway-1/gentx/gentx-5173214e9616c7513ff75d938e7ade92a5d7bcc2.json

Added WhisperNode's gentx for Archway mainnet genesis

WhisperNode gentx

---

_IBC/archway-crescent.json
_IBC/archway-persistence.json
_IBC/archway-shentu.json
_IBC/archway-tgrade.json
_IBC/archway-umee.json

- Archway <> Umee
- Archway <> Persistence
- Archway <> crescent
- Archway <> Shentu
- Archway <> Tgrade

New relayer paths are added for Archway

---

_IBC/constantine-3-axelartestnet.json
_IBC/constantine-3-cosmoshubtestnet.json
_IBC/constantine-3-osmosistestnet.json

Probably due to issues with constantine rpc old ibc clients expired

fix: Update ibc paths for constantine

---

_IBC/archway-agoric.json
_IBC/archway-kujira.json
_IBC/archway-umee.json

This adjusts pre-existing chains, to ensure fee granter availability for kjnodes relayer services.

Add kjnodes to operators

---

_IBC/archway-noble.json

add relayer address on Archway <-> Noble

---

.github/workflows/feegrant.yaml
scripts/feegrant.sh

This PR will add workflow to automatically create the fee grant when an operator is added to one of the `_IBC` paths

feat: fee grant creation workflow

---

_IBC/archway-nois.json
archway/chain.json
testnets/archwaytestnet/chain.json

This PR adds Trivium's API endpoints and relay operators.

Add Trivium infra

---

devnets/_IBC/archwaydevnet-osmosistestnet.json

A new IBC path for new titus-2 devnet.

feat: Add a new IBC path for titus-2<->osmosistestnet

---

_IBC/agoric-archway.json
_IBC/archway-axelar.json
_IBC/archway-bitcanna.json
_IBC/archway-cosmoshub.json
_IBC/archway-decentr.json
_IBC/archway-gravitybridge.json
_IBC/archway-jackal.json
_IBC/archway-kujira.json
_IBC/archway-noble.json
_IBC/archway-nois.json
_IBC/archway-omniflixhub.json
_IBC/archway-osmosis.json
_IBC/archway-quicksilver.json
_IBC/archway-secretnetwork.json
_IBC/archway-umee.json
ibc_data.schema.json

This PR adds discord IDs for IBC paths that can be used to notify users when there's problems in IBC related incidents

feat: add discord ids to IBC paths

---

_IBC/archway-decentr.json

Add "AM Solutions" to archway-decentr.json

---

_IBC/archway-neutron.json

Channel requested by Abstract team, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` archway-neutron

---

_IBC/archway-neutron.json

Updated archway-neutron.json

---

_IBC/archway-cosmoshub.json
_IBC/archway-osmosis.json

Archway <> Cosmoshub
Archway <> Osmosis

Add Stakely Relayer paths

---

_IBC/archway-sentinel.json

Send from Sentinel:
https://www.mintscan.io/sentinel/tx/38D7CD46337242462645290CF349772D55045552A1C1C685AE739E49E91905C4?height=15127061
Received on Archway:
https://www.mintscan.io/archway/tx/043C412E5AA00F98D69E0AF9966701D40FC529325678BF3333E2609DA36FE8AB?height=3471719
Send from Archway:
https://www.mintscan.io/archway/tx/BCF60BFE31CE6E62FAC1FE18EDE1B271E2AED8D31906A4831286905361028A2E?height=3471699
Received on Sentinel:
https://www.mintscan.io/sentinel/tx/11104D30676F9CB0C0724AB0B29734496F9E743481094805711125BF23AEEBF2?height=15127070

Add ARCHWAY<>SENTINEL

---

_IBC/andromeda-archway.json

This is to get them registered for the feegrant

add all l5 addresses

---

_IBC/archway-injective.json

Add DSRV Relayer information on the Archway <> Injective

Add DSRV Relayer on the Archway <> Injective

---

_IBC/archway-nibiru.json

`IBC Channel Open Confirm` on [Nibiru Tx FA82E24DA11A32F4828FDBFC403FB584CFBBA33168012283EB0B97BEEF8B57CD](https://explorer.nibiru.fi/cataclysm-1/tx/FA82E24DA11A32F4828FDBFC403FB584CFBBA33168012283EB0B97BEEF8B57CD).

Add archway-nibiru IBC

---

archway/chain.json

Synced it with https://github.com/cosmos/chain-registry/blob/master/archway/chain.json that has a more recent version of it

fix: Update chain.json

---

_IBC/archway-jackal.json

adding jackal labs jackal <> arch relayer

adding jackal labs relayer

---

archway/chain.json

Added fixed GlobalStake/Luckfriday RPC nodes

Update chain.json - Added GlobalStake/Luckfriday RPC nodes

---

archway/chain.json

This PR aims to add Chainroot resources and endpoints to archway documents

feat: add Chainroot resources and info
